SansthonAdminBundle_admin_sansthon_admin_bundle_Stock:
    resource: "@SansthonAdminBundle/Controller/Stock/"
    type:     admingenerator
    prefix:   /admin/sansthon_admin_bundle/stock

SansthonAdminBundle_admin_sansthon_admin_bundle_Role:
    resource: "@SansthonAdminBundle/Controller/Role/"
    type:     admingenerator
    prefix:   /admin/sansthon_admin_bundle/role

SansthonAdminBundle_admin_sansthon_admin_bundle_Perte:
    resource: "@SansthonAdminBundle/Controller/Perte/"
    type:     admingenerator
    prefix:   /admin/sansthon_admin_bundle/perte

SansthonAdminBundle_admin_sansthon_admin_bundle_Personne:
    resource: "@SansthonAdminBundle/Controller/Personne/"
    type:     admingenerator
    prefix:   /admin/sansthon_admin_bundle/personne

SansthonAdminBundle_admin_sansthon_admin_bundle_Etape:
    resource: "@SansthonAdminBundle/Controller/Etape/"
    type:     admingenerator
    prefix:   /admin/sansthon_admin_bundle/etape

SansthonAdminBundle_admin_sansthon_admin_bundle_type:
    resource: "@SansthonAdminBundle/Controller/Type/"
    type:     admingenerator
    prefix:   /admin/sansthon_admin_bundle/type

sansthon_prod:
    resource: "@SansthonProdBundle/Controller/"
    type:     annotation
    prefix:   /

AdmingeneratorGeneratorBundle_Dashboard:
    resource: "@AdmingeneratorGeneratorBundle/Resources/config/routing.yml"
    prefix:   /
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
