<?php

namespace Sansthon\ProdBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtapefilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapefilleRepository extends EntityRepository
{
}
