<?php

namespace Sansthon\ProdBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapeRepository extends EntityRepository
{
  public function findAllOrderedByDisplayorder()
  {
    return $this->getEntityManager()
      ->createQuery('SELECT e FROM SansthonProdBundle:Etape e ORDER BY e.displayorder ASC')
      ->getResult();
  }
}
