<?php

namespace Sansthon\ProdBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatRepository extends EntityRepository
{
  /***
   * Cancel current Etat
   *
   *
   *
   */

  public function cancel($id) {
    /* onrecupere l'etat*/
    $etat = $this->find($id);

    if($etat->getEtapeorigine()){
      $stockorigin= $this->_em->getRepository("SansthonProdBundle:Stock")->getByEtapeAndType($etat->getEtapeorigine(),$etat->getType());
      $stockorigin->addValue($etat->getQuantite());
    }
    $this->get('session')->getFlashBag()->add('notice', $etat->getEtape()." de ".$etat->getType().' '.$etat->getType()->getNom().' incrémenté de '.$etat->getQuantite()."."  );
    /* quantie refaite suppression de l'etat*/
    $this->_em->remove($etat);
    $this->_em->flush();
  }
}
