generator: admingenerator.generator.doctrine
params:
  model: Sansthon\ProdBundle\Entity\Attributionrole
  namespace_prefix: Sansthon
  bundle_name: AdminBundle
  fields: ~

builders:
  list:
    params:
      title: Attribution des rôles
      display:  [id,role,personne]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: [id,role,personne]
  new:
    params:
      title: Nouvelle Attribution
      display: [role,personne]
      actions:
        save: ~
        list: ~
  edit:
    params:
      title: "Vous modifier l'attribution  \"%object%\"|{ %object%: Attributionrole.id }|"
      display: [role,personne]
      actions:
        save: ~
        list: ~
  show:
    params:
      title: "Description de l'attribution  \"%object%\"|{ %object%: Attributionrole.id }|"
      display: [id,role,personne]
      actions:
        list: ~
        new: ~
  delete: ~
