generator: admingenerator.generator.doctrine
params:
  model: Sansthon\ProdBundle\Entity\Personne
  namespace_prefix: Sansthon
  bundle_name: AdminBundle
  fields: ~

builders:
  list:
    params:
      title: Liste des Personnes
      display: [prenom, nom ]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: ~
  new:
    params:
      title: Ajouter une Personne
      display: [prenom, nom , adresse, telephone,roles]
      actions:
        save: ~
        list: ~
  edit:
    params:
      title: "Modification des information concernant : \"%object%\"|{ %object%: Personne.nom }|"
      display: [prenom, nom , adresse, telephone,roles]
      actions:
        save: ~
        list: ~
  show:
    params:
      title: "Information concernant : \"%object%\"|{ %object%: Personne.nom }|"
      display: [prenom, nom , adresse, telephone,roles]
      actions:
        list: ~
        new: ~
  delete: ~
