generator: admingenerator.generator.doctrine
params:
  model: Sansthon\ProdBundle\Entity\Perte
  namespace_prefix: Sansthon
  bundle_name: AdminBundle
  fields: ~

builders:
  list:
    params:
      title: List des Pertes
      display: ~
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: ~
  new:
    params:
      title: Création d'une pertes
      display: [id]
      actions:
        save: ~
        list: ~
  edit:
    params:
      title: "Modification de la pertes \"%object%\"|{ %object%: Perte.id }|"
      display: ~
      actions:
        save: ~
        list: ~
  show:
    params:
      title: "Description de la perte \"%object%\"|{ %object%: Perte.id }|"
      display: ~
      actions:
        list: ~
        new: ~
  delete: ~
