generator: admingenerator.generator.doctrine
params:
  model: Sansthon\ProdBundle\Entity\Role
  namespace_prefix: Sansthon
  bundle_name: AdminBundle
  fields: ~

builders:
  list:
    params:
      title: Liste des Roles
      display: [nom,commentaire]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: ~
  new:
    params:
      title: Ajouter un nouveau Roles
      display: [nom,commentaire]
      actions:
        save: ~
        list: ~
  edit:
    params:
      title: "Edition du Role \"%object%\"|{ %object%: Role.id }|"
      display: [nom,commentaire]
      actions:
        save: ~
        list: ~
  show:
    params:
      title: "Description du Role \"%object%\"|{ %object%: Role.id }|"
      display: [nom,commentaire]
      actions:
        list: ~
        new: ~
  delete: ~
