generator: admingenerator.generator.doctrine
params:
  model: Sansthon\ProdBundle\Entity\Stock
  namespace_prefix: Sansthon
  bundle_name: AdminBundle
  fields: ~

builders:
  list:
    params:
      title: Etat des Stocks
      display: ~
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: ~
  new:
    params:
      title: Ajouter un Stock
      display: ~
      actions:
        save: ~
        list: ~
  edit:
    params:
      title: "Modifcation du stock de \"%object%\" a l'etape %etape%|{ %object%: Stock.type, %etape% : Stock.etape }|"
      display: ~
      actions:
        save: ~
        list: ~
  show:
    params:
      title: "Description du Stock de  \"%object%\" a l'etape %etape% |{ %object%: Stock.type, %etape% : Stock.etape }|"
      display: ~
      actions:
        list: ~
        new: ~
  delete: ~
