generator: admingenerator.generator.doctrine
params:
  model: Sansthon\ProdBundle\Entity\Type
  namespace_prefix: Sansthon
  bundle_name: AdminBundle
  fields: ~

builders:
  list:
    params:
      title: Listes des Références
      display: [id,nom,reference]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: ~
  new:
    params:
      title: Nouvelle Référence
      display:
        None: [nom,reference,objectif,commentaire]
      actions:
        save: ~
        list: ~
  edit:
    params:
      title: "You're editing the object \"%object%\"|{ %object%: Type.reference }|"
      display: [nom,reference,objectif,commentaire]
      actions:
        save: ~
        list: ~
  show:
    params:
      title: "You're viewing the object \"%object%\"|{ %object%: Type.reference }|"
      display: ~
      actions:
        list: ~
        new: ~
  delete: ~
